### ISSUE TITLE
How to get all recipe data using scrapper from specific website?

### ISSUE THREAD

**Issue by irfanpb** [jadkins89/Recipe-Scraper#14]
Hi,

We are having a query to use the scrapper library for getting the data of all recipes using it. The current demo of the library only allowed to put a single URL and gives the scraped data.

But if we want to sync all the recipes from the following website. How it can be achieved? 

1.https://www.yummly.com/
2. https://www.woolworths.com.au/
3. https://www.thespruceeats.com/
4. https://www.myrecipes.com/
5. https://www.seriouseats.com/
6. https://www.food.com/
7. https://www.foodnetwork.com/
8. https://www.finecooking.com/

Thanks & Regards.

**Comment by jadkins89** [comment]
You'd like to scrape the entirety of a website? If that's the case you'd need to figure out how the domain paths of each website are structured and see if there is some iterable way to run through all the ones containing recipes (or some brute force strategy).

The way this library works is by making an HTTP request to a URL and then combing through the HTML that it responds with. Because of this, you'd need to do the requests individually. You could certainly create a wrapper function with this library that takes multiple urls and iterates through them though.
