### ISSUE TITLE
Requesting Sites

### ISSUE THREAD

**Issue by MilanParikh** [jadkins89/Recipe-Scraper#31]
So I noticed these two websites, and probably many more use the same plugin for their recipes, I hope it's easier to incorporate one scraper for any sites that use this? 

Here's a couple example websites:
https://tastesbetterfromscratch.com/
https://www.recipetineats.com/

**Comment by jadkins89** [comment]
This is months old so sorry if this response is irrelevant but you are right. They are using a Word Press recipe template. When I see this (or other commonly used templates), I typically copy another scrape I've already written and tweak it to conform to the website I'm working on. There is usually still some variation, since CMS's usually allow for flexibility.

If I had more time, in the future it would be nice to make these scrapes less brittle but this will typically come at the cost of precision since you are trying to guess where elements / text is located.

**Comment by jadkins89** [comment]
I've added your two example sites, closing this for now.
